import { ClerkProvider } from "@clerk/nextjs";
import "../styles/globals.css";
import { Orbitron } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const orbitron = Orbitron({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <ClerkProvider>
      <html lang="en">
        <body
          className={`m-5 rounded flex  min-h-screen text-[#eeeeee] ${orbitron.className}`}
        >
          {" "}
          <NavBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
